name: sabore_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0  # Navegação
  dio: ^5.6.0  # HTTP requests
  flutter_riverpod: ^2.5.0  # Gerenciamento de estado
  flutter_secure_storage: ^9.0.0  # Armazenar JWT
  freezed_annotation: ^2.4.1
  intl_phone_field: ^3.2.0
  http: ^1.2.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0  # Para gerar código com freezed (se usar)
  json_serializable: ^6.7.0  # Para gerar modelos (se usar)

flutter:
  uses-material-design: true
  assets:
    - assets/images/onb1.jpg
    - assets/images/onb2.jpg
    - assets/images/onb3.jpg
    - assets/images/onb4.jpg
    - assets/images/chef.jpg
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/pudim.png
    - assets/images/google.png
    - assets/images/apple-logo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700