// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvLCMzuRk0r6plXLeyL83-2n8DWPXqZwM',
    appId: '1:650438256089:web:09c6601c01f767f91fe5c8',
    messagingSenderId: '650438256089',
    projectId: 'sabore-app-bd837',
    authDomain: 'sabore-app-bd837.firebaseapp.com',
    storageBucket: 'sabore-app-bd837.firebasestorage.app',
    measurementId: 'G-V640EM1PER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn47fSyc3lxX0OjExSS8EVhoS1iXDxnJ0',
    appId: '1:650438256089:android:8eb8f0293b9bcb301fe5c8',
    messagingSenderId: '650438256089',
    projectId: 'sabore-app-bd837',
    storageBucket: 'sabore-app-bd837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTLYHs3yxx93BO-4jDfLXXxJC3hW0hTqg',
    appId: '1:650438256089:ios:578de02025bdbab41fe5c8',
    messagingSenderId: '650438256089',
    projectId: 'sabore-app-bd837',
    storageBucket: 'sabore-app-bd837.firebasestorage.app',
    iosBundleId: 'com.example.saboreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTLYHs3yxx93BO-4jDfLXXxJC3hW0hTqg',
    appId: '1:650438256089:ios:578de02025bdbab41fe5c8',
    messagingSenderId: '650438256089',
    projectId: 'sabore-app-bd837',
    storageBucket: 'sabore-app-bd837.firebasestorage.app',
    iosBundleId: 'com.example.saboreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvLCMzuRk0r6plXLeyL83-2n8DWPXqZwM',
    appId: '1:650438256089:web:7ce65cf2a25f1f691fe5c8',
    messagingSenderId: '650438256089',
    projectId: 'sabore-app-bd837',
    authDomain: 'sabore-app-bd837.firebaseapp.com',
    storageBucket: 'sabore-app-bd837.firebasestorage.app',
    measurementId: 'G-ZXEMEGG9NF',
  );
}
